### ISSUE TITLE
EXC_BAD_ACCESS when calling updateUser

### ISSUE THREAD

**Issue by tebs1200** [helpcrunch/sdk-cocoapods#1]
I'm using the HelpCrunch SDK in a Swift project. It's causing the app to crash when I invoke `updateUser`.

 - Swift Language Version: 5
 - HelpCrunchSDK Version: 1.1.14

I've recently converted the project to Swift 5 which is when the issue started occurring. Is the SDK compatible with Swift 5?

Here's the line that's causing the crash:
```
HelpCrunch.updateUser(attributes as [AnyHashable : Any], completionHandler: nil)
```

I added a breakpoint right before the crash to capture the value of `attributes`:
![attributes-dictionary-values](https://user-images.githubusercontent.com/9997294/63236151-fb0bcb00-c27f-11e9-9d3c-dfcf5038e5fc.png)

**Comment by Fishkiller** [comment]
Fixed in 1.1.15 . Meanwhile try to provide completionHandler
