### ISSUE TITLE
HelpCrunch UI not fullscreen

### ISSUE THREAD

**Issue by capitanomikejobs** [helpcrunch/sdk-cocoapods#2]
Hello,

after update to iOS 13 when I try to present your widget it is not opened in full screen mode!

Cocoapods (if applicable): 1.8.1
Helpcrunch SDK version: 1.1.15
iOS: 13
Xcode: 11
Device/Simulator: both
Device/Simulator language: en 

Steps to reproduce the issue:
1) create an new Xcode project for iOS 13
2) add Helpcrunch SDK
3) show the chat widget trough a button 
![IMG_5642FF1A327B-1](https://user-images.githubusercontent.com/2248807/65892617-e3f3e900-e3a6-11e9-86fe-3928560e1627.jpeg)

**Comment by Fishkiller** [comment]
Please, check new version of out sdk here: https://github.com/helpcrunch/helpcrunchsdk-ios/
